$targetPath = ".\src\pureCython\"
 
Get-ChildItem -Path $targetPath -Recurse -File | ForEach-Object {
    if ($_.Extension -eq ".pyd" -or (Get-Content $_ -First 1) -match '^/\* Generated by Cython ') {
        Write-Host "Deleting file: $($_)"
        Remove-Item $_ -Force
    }
}
